### PR TITLE
Add check if pods in ns before delete

### PR DESCRIPTION
**Pull request by itdove**
Signed-off-by: Dominique Vernier <dvernier@redhat.com>

### CODE REVIEW

**Comment by leena-jawale** [comment]
There is namespace `openahift-config` which does not have pod. In that case, it will delete that namespace

**Comment by hanqiuzh** [comment]
agree with @leena-jawale , we may want another rule like regex `openshift-*`?

**Comment by jnpacker** [comment]
I wasn't sure how far to go. But this would stop options like openshift-josh1 and openshift-east-cluster01

**Comment by jnpacker** [comment]
But, this just means we won't delete the namespace so I can get onboard with openshift-*. Just make sure it gets documented.

**Comment by itdove** [comment]
Guys, this a first step until they accept an overall cr containing all information to start an import... as we proposed few months ago !
Pleat just accept this change as a temporary solution !

**Comment by hanqiuzh** [comment]
Will approve this pr for now. Most openshift namespaces seems are either protected by webhook, or it can generate itself.
```
# oc delete ns openshift-config
Error from server (Forbidden): namespaces "openshift-config" is forbidden: this namespace may not be deleted
# oc delete ns openshift-dns
namespace "openshift-dns" deleted
# oc get ns openshift-dns
NAME            STATUS   AGE
openshift-dns   Active   22s
//!!!!!
# oc delete ns openshift-kube-apiserver 
namespace "openshift-kube-apiserver" deleted
# oc get ns openshift-kube-apiserver 
NAME                       STATUS   AGE
openshift-kube-apiserver   Active   32s
```

**Pull request merged**
